# Generated by Django 4.2 on 2025-02-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.jugador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.partit'),
        ),
    ]
